### PR TITLE
bash completion for tp command

### PR DESCRIPTION
**Pull request by gsouf**
I just added the ability to access the teleportable directory to the completion. It will read the `~/.tp_history` and put them in the completion list in addition of the default completion

### CODE REVIEW

**Comment by alvinj** [comment]
Thanks for the Bash completion code. I'm traveling at the moment without much internet access, but I'm going to see if I can test and merge this today.

**Comment by gsouf** [comment]
That's ok !

I just read again the completion code, and i need to bring a change. I know that some people use an alias for `ls` aliasing it with `ls -l`. It wont work with the current code (i dont use to alias it, then it worked nice with my tests).

I will update it in a couple of minutes

**Comment by alvinj** [comment]
I'm sorry for the long delay, the internet access has been very bad. I'll be back home next week, and I'll merge this in then. Thanks for the contribution, I really appreciate it!

**Comment by alvinj** [comment]
Just a quick note to let you know that I finally quit traveling and got to a point of good internet access, and just merged your code in. Thanks so much, this is awesome!

**Comment by gsouf** [comment]
You're welcome, this command is very usefull, it just needed the completion to be... complete !

**Pull request merged**
